server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:journal
    driverClassName: org.h2.Driver
    username: admin
    password: rootroot
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect.security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/journal-de-bord
          jwk-set-uri: http://localhost:8083/auth/realms/journal-de-bord/protocol/openid-connect/certs